name: Continuous Deployment
on:
  push:
    branches:
      - canary46

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package.json') }}
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          registry-url: https://npm.pkg.github.com/
          node-version: '16.x'
          check-latest: true
          scope: "@enroly"
      - name: npm install and build
        run: |
          npm install
          npm run build --if-present
      - name: publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          npm run deploy
